In [4]:
a = set([0,1,2,3])
b = set([0,2,5,6])
a | b

{0, 1, 2, 3, 5, 6}

In [1]:
import torch

In [12]:
a = torch.tensor([0,1,2,3,4,5,6,7,8,9,10,11,12, 1110])
a.to(torch.int8)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 86],
       dtype=torch.int8)

In [6]:
a.to(torch.int8)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 21],
       dtype=torch.int8)

In [2]:
d = {'a':[10]}
for k, v in d.items():
    print(k)
    print(v)

a
[10]


In [1]:
import pickle

In [2]:
with open('/home/dghilardi/mention_clustering/mention-clustering/zeshel_processed/dataset.pkl', 'rb') as f:
    dataset = pickle.load(f)

In [9]:
import torch
a = torch.stack([torch.tensor([0,1,2]), torch.tensor([3,4,5])])

In [61]:
from transformers import AutoTokenizer, AutoModel
import torch
import numpy as np

In [108]:
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
model = AutoModel.from_pretrained('bert-base-uncased')

In [117]:
a = ['Last', 'year', 'Messi', 'has', 'scored', 'two', 'goals']
b = 'Last year Messi      has scored two goals'

In [118]:
b.split(' ')

['Last', 'year', 'Messi', '', '', '', '', '', 'has', 'scored', 'two', 'goals']

In [116]:
tok = tokenizer(a, is_split_into_words=True, return_tensors='pt')

In [113]:
start, end = tok.word_to_tokens(3)

In [115]:
end

6

In [96]:
s = 'Last year ' + tokenizer.pad_token + ' Cristiano Ronaldo el mas grande ' + tokenizer.pad_token + ' scored two goals.'
y = ' Last year Cristiano Ronaldo el mas grande scored two goals'

In [97]:
s_token = tokenizer([s], return_tensors='pt', max_length=15, padding='max_length')
y_token = tokenizer([y], return_tensors='pt', max_length=15, padding='max_length')

In [98]:
print(s_token['input_ids'])
print(y_token['input_ids'])

tensor([[  101,  2197,  2095,     0, 13675,  2923, 15668,  8923,  2080,  3449,
         16137,  9026,     0,  3195,  2048,  3289,  1012,   102]])
tensor([[  101,  2197,  2095, 13675,  2923, 15668,  8923,  2080,  3449, 16137,
          9026,  3195,  2048,  3289,   102]])


In [104]:
pad_idx = torch.argwhere(s_token['input_ids'][0]==0)[:2].flatten().numpy()
mention_idx = [pad_idx[0], pad_idx[1]-1]

In [105]:
retain_idx = list(set(np.arange(s_token['input_ids'][0].shape[0])) - set(pad_idx))

In [106]:
s_token_clean = s_token['input_ids'][0][retain_idx]

In [107]:
s_token_clean[mention_idx[0]:mention_idx[1]]

tensor([13675,  2923, 15668,  8923,  2080,  3449, 16137,  9026])

In [34]:
s_output = model(**s_token)
y_output = model(**y_token)

In [37]:
s_output.last_hidden_state[0][5].sum()

tensor(-10.3219, grad_fn=<SumBackward0>)

In [38]:
y_output.last_hidden_state[0][4].sum()

tensor(-10.0465, grad_fn=<SumBackward0>)

In [43]:
lc = 'Last year in the final match'
et = 'Messi'
rc = 'has scored two goals.'

In [44]:
lc_len = len(lc)
et_len = len(et)
rc_len = len(rc)

In [45]:
frase = lc +' '+et+' '+rc

In [46]:
frase

'Last year in the final match Messi has scored two goals.'

In [47]:
et_pos = [lc_len+1,lc_len+1+et_len]

In [49]:
frase[et_pos[0]:et_pos[1]]

'Messi'

In [53]:
tok = tokenizer(frase, return_tensors='pt')

In [56]:
tok['input_ids']

tensor([[ 101, 2197, 2095, 1999, 1996, 2345, 2674, 6752, 2072, 2038, 3195, 2048,
         3289, 1012,  102]])

In [60]:
tok.

TypeError: argument 'char_pos': 'list' object cannot be interpreted as an integer